name: Release Blender Addons

on:
  push:
    paths:
      - 'UMAConverterBlender/**'
      - 'DazUMAConverterBlender/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip UMAConverterBlender
        run: zip -r UMAConverterBlender.zip UMAConverterBlender/

      - name: Zip DazUMAConverterBlender
        run: zip -r DazUMAConverterBlender.zip DazUMAConverterBlender/

      - name: Get current date and time
        id: date
        run: echo "now=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.date.outputs.now }}
          name: Release ${{ steps.date.outputs.now }}
          draft: false
          prerelease: false
          files: |
            UMAConverterBlender.zip
            DazUMAConverterBlender.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

